language: node_js
node_js:
  -"8"
sudo: required
services:
  - docker

before_install:
  - docker build -t marinc/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true marcin/docker-react npm run test